name: Flutter CI/CD

on:
  push:
    tags:
      - v*
      
jobs:
  flutter_test:
    name: Flutter Tests
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get
      
      - name: Flutter Analyze
        run: flutter analyze

      - name: Flutter Format Lib
        run: flutter format --dry-run --set-exit-if-changed lib/

      - name: Flutter Format Test
        run: flutter format --dry-run --set-exit-if-changed test/

      - name: Run Unit Tests
        run: flutter test --coverage

      - name: Save Tests Results
        run: flutter test --machine > test-results.json

      - uses: dorny/test-reporter@v1.4.2
        with:
          name: test-results
          path: test-results.json
          reporter: flutter-json
      
      - uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          min_coverage: 80
  
  build_ios:
    name: Build iOS
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: '3.0.5'

      - run: flutter pub get
      - run: flutter clean
      - run: flutter build ios --release --no-codesign    
      - run: mkdir -p build/ios/iphoneos/Payload
      - run: mv build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload
      - run: cd build/ios/iphoneos
      - run: zip -r /Payload . -i /app.ipa
      - run: rm -rf /Payload
      - name: iOS Bundle
        uses: actions/upload-artifact@v2.1.4
        with:
          name: iosbundle
          path: build/ios/iphoneos/app.ipa

  build_android:
    name: Build Flutter (Android)
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with:
            channel: "stable"
            flutter-version: '3.0.5'
            architecture: x64
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build appbundle
      - name: Android Bundle
        uses: actions/upload-artifact@v2.1.4
        with:
          name: appbundle
          path: build/app/outputs/bundle/release/app-release.aab